volumes:
  mongo_data:

services:
  services:
    posgres:
      hostname: posgres
      image: ankane/pgvector
      ports:
       - 5432:5432
      restart: always
      environment:
        - POSTGRES_DB=tiara
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_HOST_AUTH_METHOD=trust
      # volumes:
      #  - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # ml_service:
  #   build:
  #     context: ./ml
  #     dockerfile: Dockerfile
  #   container_name: ml_service
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - mongodb
  #   develop:
  #     # Create a `watch` configuration to update the app
  #     watch:
  #       # Sync the working directory with the `/app` directory in the container
  #       - action: sync
  #         path: ./ml
  #         target: /app
  #         # Exclude the project virtual environment
  #         ignore:
  #           - .venv/

  #       # Rebuild the image on changes to the `pyproject.toml`
  #       - action: rebuild
  #         path: ./ml/pyproject.toml
